<a href="https://colab.research.google.com/github/pnijsters/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
!nvidia-smi

Tue Oct  8 18:13:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Introduction to tensors

### Creating tensors

In [29]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [27]:
scalar.ndim

0

In [28]:
scalar.item()

7

In [46]:
# vector
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [44]:
vector.ndim

1

In [45]:
vector.shape

torch.Size([7])

In [48]:
# MATRIX
MATRIX=torch.tensor([[7,8,9],[5,6,7]])
MATRIX

tensor([[7, 8, 9],
        [5, 6, 7]])

In [49]:
MATRIX.ndim

2

In [50]:
MATRIX[0]

tensor([7, 8, 9])

In [38]:
MATRIX[1]

tensor([5, 6])

In [51]:
MATRIX.shape

torch.Size([2, 3])

In [61]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[3,2,1],[6,5,4],[9,8,7]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[3, 2, 1],
         [6, 5, 4],
         [9, 8, 7]]])

In [62]:
TENSOR.ndim

3

In [63]:
TENSOR.shape

torch.Size([2, 3, 3])

In [64]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
TENSOR[1] [1]

tensor([6, 5, 4])